name: Deploy development

on:
  pull_request:
    branches: ["development"]
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image and push to repositories
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: login to hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: davidbrsp/snake:development

      - name: Deploying using SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          script: |
            docker image pull davidbrsp/snake:development
            docker container stop snake-container
            docker container rm snake-container
            docker container run -d --name snake-container -p 80:80 davidbrsp/snake
